"""inclusao do campo status

Revision ID: 657720ef826e
Revises: 6e06513efa98
Create Date: 2025-07-26 13:19:38.560973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657720ef826e'
down_revision: Union[str, Sequence[str], None] = '6e06513efa98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('stauts', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'stauts')
    # ### end Alembic commands ###
