"""exclusao do campo status

Revision ID: 6e06513efa98
Revises: 4b00118538be
Create Date: 2025-07-26 13:18:34.824348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e06513efa98'
down_revision: Union[str, Sequence[str], None] = '4b00118538be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'stauts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('stauts', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
